### ISSUE TITLE
Table Column Alignment

### ISSUE THREAD

**Issue by chrisgriffith** [chrisgriffith/glasstone-dolan#31]
Some tables need at right alignment for the data in a particular column.

**Comment by meyerweb** [comment]
This one’s going to be tricky, because CSS doesn’t allow `text-align` to be applied to columns, so I can’t class `<col>` elements the way I did row groups and rows.  The choices I can see are classing every cell that needs a specific alignment (yuck), or table-specific style sheets with `:nth-child` selectors to enforce alignment (also yuck, but less so).

Related: there is still, after 25 years, **still** no way to align table column text on a character like a period.  So the columns that have decimal-place alignment will either never be fixed, or will most likely require massive markup-level intervention to make work.  (Spacer `<span>`s, anyone?)

**Comment by meyerweb** [comment]
I think this one is closed now, thanks to PR #36.

**Comment by meyerweb** [comment]
This should be closed, but I can’t do it.

**Comment by chrisgriffith** [comment]
Closed
