### ISSUE TITLE
Table Alignment

### ISSUE THREAD

**Issue by chrisgriffith** [chrisgriffith/glasstone-dolan#33]
Some tables render misaligned with respect to the page. 

Table 7.35
Table 8.41
Table 12.17
Table 12.21

Sample;
![Screen Shot 2022-04-01 at 10 08 34 AM](https://user-images.githubusercontent.com/527875/161310175-3cfb0e84-f6dd-406a-8f1f-12ec4b014127.png)

**Comment by meyerweb** [comment]
I came up with a fix for this, and while it definitely helps with tables like 7/35, it causes some of the smaller “wide” tables to get unhelpfully wide at very wide window widths.  Will probably submit a PR for this fix and think further about how to deal with this (currently pondering changing some `wide table` classes to `oversize table` or similar in order to distinguish between the ones that need a touch more room, and those that are enormous).
